/* Copyright 2022 Zinc Labs Inc. and Contributors
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
 */

package routes

import (
	"io/fs"
	"net/http"

	"github.com/gin-gonic/gin"

	"github.com/zincsearch/zincsearch/docs" // generated by Swag CLI
)

// swaggerHandler serves /swagger/*any. The page is built by vite as a second entry
// (frontend/swagger-ui/index.html, see frontend/vite.config.ts); its JS/CSS live under
// /ui/assets/ like the console, so only the index page and the OpenAPI document are served here.
func swaggerHandler(front fs.FS) (gin.HandlerFunc, error) {
	index, err := fs.ReadFile(front, "swagger-ui/index.html")
	if err != nil {
		return nil, err
	}
	return func(c *gin.Context) {
		switch c.Param("any") {
		case "/", "/index.html":
			c.Data(http.StatusOK, "text/html; charset=utf-8", index)
		case "/doc.json":
			c.Data(http.StatusOK, "application/json; charset=utf-8", []byte(docs.SwaggerInfo.ReadDoc()))
		default:
			c.AbortWithStatus(http.StatusNotFound)
		}
	}, nil
}
